import type { Metadata } from 'next';
import './globals.css';
import NavigationLinks from './components/NavigationLinks';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <NavigationLinks />
        {children}
        <Footer />
      </body>
    </html>
  );
}
